# Generated by Django 4.0.4 on 2022-05-21 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=28)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('is_author', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='uploadedtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
