# Generated by Django 4.0.4 on 2022-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_user_article_uploadedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
