# Generated by Django 4.0.4 on 2022-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
