# Generated by Django 4.0.4 on 2022-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_author_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
