# Generated by Django 4.0.4 on 2022-07-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_delete_user_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
